require: rubocop-rspec

Style/Documentation:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

Metrics/BlockLength:
  ExcludedMethods:
    - describe
    - context
    - let
    - shared_examples
    - class_methods
    - included
