env:
  - DATABASE_URL=postgres://postgres:@localhost:5432/travis_ci_test
language: ruby
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle exec rake db:migrate --trace
  - bundle exec rspec
bundler_args: --binstubs=./bundler_stubs
